In [53]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [54]:
ch_arr2=np.array(['Supervised','unsupervised','semi-supervised','reinforcement'])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [55]:
cleared_arr=np.char.replace(low_arr,"-"," ")
cleared_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [56]:
array1=np.array([1,2,3])
array1.dtype

dtype('int32')

In [57]:
char_arr.dtype

dtype('<U1')

In [58]:
low_arr.dtype

dtype('<U15')

In [59]:
ch_arr2.dtype

dtype('<U15')

In [60]:
array2=np.array([1,2,3],dtype='f')
array2

array([1., 2., 3.], dtype=float32)

In [61]:
array3conv=array2.astype('F')
array3conv

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [62]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

In [63]:
arr1=np.ones(3)
arr1

array([1., 1., 1.])

In [64]:
arr2=np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
arr3=np.random.random(9)
arr3

array([0.55587445, 0.36213986, 0.30920867, 0.20882092, 0.8548717 ,
       0.74124575, 0.04358263, 0.52783431, 0.7106518 ])

In [66]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [72]:
numones=np.ones((3,2))
numones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [79]:
dimones=np.ones((3,3,3))
dimones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
dimones.ndim

3

In [76]:
dimones.dtype

dtype('float64')

In [85]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
division=arr1/arr2
division

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [81]:
addition

array([[ 8, 10, 12],
       [14, 16, 18]])

In [86]:
power=np.power(arr1,arr2)
print(power)

[[          1         256       19683]
 [    1048576    48828125 -2118184960]]


In [87]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])
result=array2d+array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [90]:
result.shape

(2, 3)

In [92]:
range_array=np.arange(0,10,1)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a=np.random.randint(low=1,size=5)
a

array([0, 0, 0, 0, 0])

In [99]:
np.concatenate([arr1,arr2])


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [104]:
flatarr=arr1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [105]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
np.info(np.ndarray.ndim)


Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3
